jobs/urls.py
from django.conf.urls import url
from .views import *

app_name = 'jobs'

urlpatterns = [
    url(r'^addjobs/$', addjobs_view, name='addjobs'),
    url(r'^ilandetay/(?P<pk>[0-9]+)/$', isİlaniDetay, name='ilandetay'),
    url(r'^ilanguncelle/(?P<pk>[0-9]+)/$', isİlaniGuncelle, name='ilanguncelle'),
    url(r'^ilansil/(?P<pk>[0-9]+)/$', isİlaniSil, name='ilansil'),
    url(r'^ilanlarim/$', ilanlarim, name='ilanlarim'),
    url(r'^ilanlar/$', isİlaniGoruntule, name='ilanlar'),
    url(r'^stajekle/$', stajIlaniEkle, name='stajekle'),
    url(r'^stajilanlari/$', stajİlaniGoruntule, name='stajilanlari'),
    url(r'^stajilanidetay/(?P<pk>[0-9]+)/$', stajİlaniDetay, name='stajilanidetay'),
    url(r'^stajilaniguncelle/(?P<pk>[0-9]+)/$', stajİlaniGuncelle, name='stajilaniguncelle'),
    url(r'^stajilanisil/(?P<pk>[0-9]+)/$', stajİlaniSil, name='stajilanisil'),
]

obs/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from jobs.views import bildirimIcin
from django.contrib.auth import views as auth_views
from accounts.views import *
from grafik.views import HomeView, ChartData, get_data




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', loginRegister, name='index'),
    url(r'^anasayfa/', bildirimIcin, name='anasayfa'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^jobs/', include('jobs.urls')),
    url(r'^jobs/', include('django.contrib.auth.urls')),
    url(r'^dersNotlari/', include('dersNotu.urls')),
    url(r'^dersNotlari/', include('django.contrib.auth.urls')),
    url(r'^belgeler/', include('belgeler.urls')),
    url(r'^belgeler/', include('django.contrib.auth.urls')),
    url(r'^randevu/', include('randevu.urls')),
    url(r'^dersicerik/', include('dersicerik.urls')),
    url(r'^machine/', include('machine.urls')),

    url(r'^api/data/$', get_data, name='api-data'),
    url(r'^grafik/charts', HomeView.as_view(), name='charts'),
    url(r'^api/chart/data/$', ChartData.as_view()),


    # Password reset links
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_complete'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/models.py
from django.db import models

class IsIlaniEkle(models.Model):
    isOzeti = models.CharField(max_length=250, null=False, blank=False)
    firma = models.CharField(max_length=250, null=False, blank=False)
    konum = models.CharField(max_length=250, null=False, blank=False)
    ilanTarihi = models.DateTimeField()
    isTanimi = models.TextField(null=False, blank=False)
    nitelikler = models.TextField(null=False, blank=False)
    sektor = models.CharField(max_length=250, null=False, blank=False)
    pozisyon = models.CharField(max_length=250, null=False, blank=False)
    pozisyonSeviyesi = models.CharField(max_length=250, null=False, blank=False)
    calismaSekli = models.CharField(max_length=250, null=False, blank=False)
    adres = models.TextField(null=False, blank=False)
    basvuruSekli = models.CharField(max_length=250, null=False, blank=False)
    sonBasvuruTarihi = models.DateField()
    ilanSahibi = models.CharField(max_length=250)
    ilanSahibiMail = models.EmailField()

    def __str__(self):
        return self.isOzeti


class stajIlani(models.Model):
    stajBaslik = models.CharField(max_length=250, null=False, blank=False)
    stajFirma = models.CharField(max_length=250, null=False, blank=False)
    stajKonum = models.CharField(max_length=250, null=False, blank=False)
    stajIlanTarihi = models.DateTimeField()
    stajBilgilendirme = models.TextField(null=False, blank=False)
    stajAdres = models.TextField(null=False, blank=False)
    stajSonBasvuruTarihi = models.DateField()
    stajIlanSahibi = models.CharField(max_length=250)
    stajIlanSahibiMail = models.EmailField()

    def __str__(self):
        return self.stajBaslik

jobs/forms.py
from django import forms
from .models import IsIlaniEkle, stajIlani

class IsIlaniEkleForm(forms.ModelForm):
    class Meta:
        model = IsIlaniEkle
        fields = ['isOzeti', 'firma', 'konum', 'isTanimi', 'nitelikler', 'sektor', 'pozisyon',
        'pozisyonSeviyesi', 'calismaSekli', 'adres', 'basvuruSekli']

class StajIlaniForm(forms.ModelForm):
    class Meta:
        model = stajIlani
        fields = ['stajBaslik', 'stajFirma', 'stajKonum', 'stajBilgilendirme', 'stajAdres']

jobs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import IsIlaniEkleForm, StajIlaniForm
from .models import IsIlaniEkle, stajIlani
from django.utils import timezone
import datetime
from accounts.models import Ogrenci, Mezun, BolumSekreteri, OgretimGorevlisi
from belgeler.models import TranskriptOgrenci, TranskriptMezun, MesajMezun, MesajOgrenci
from randevu.models import randevuMezun,randevuOgrenci,MesajRandevuMezun,MesajRandevuOgrenci
from dersicerik.models import DersIcerikMezun, MesajdersMezun

def addjobs_view(request):
    if request.method == "POST":
        form = IsIlaniEkleForm(request.POST)
        if form.is_valid():
            veri = form.save(commit=False)
            veri.ilanTarihi = timezone.now()
            veri.ilanSahibi = request.user.get_full_name()
            veri.ilanSahibiMail = request.user.email
            veri.sonBasvuruTarihi = request.POST.get('sonBasvuruTarihi')
            veri.save()
        return redirect('jobs:ilanlar')
    else:
        form = IsIlaniEkleForm(request.POST)
    return render(request, 'jobs/addjobs.html', {'form': form})

def isİlaniGoruntule(request):
    ilanlar = IsIlaniEkle.objects.all()
    bugun = datetime.datetime.now(tz=timezone.utc)

    for ilan in ilanlar:
        print(ilan.sonBasvuruTarihi.month)

    for g in request.user.groups.all():
        if g.name == 'Mezun':
            ogrenciGiris = Mezun.objects.get(user=request.user)
            ogrenciGiris.oncekiGirisIs = datetime.datetime.now(tz=timezone.utc)
            ogrenciGiris.gorulenIsId = 0
            ogrenciGiris.ilanToplam = ogrenciGiris.gorulenStajId + 0
            ogrenciGiris.save()
        if g.name == 'Öğrenci':
            ogrenciGiris = Ogrenci.objects.get(user=request.user)
            ogrenciGiris.oncekiGirisIs = datetime.datetime.now(tz=timezone.utc)
            ogrenciGiris.gorulenIsId = 0
            ogrenciGiris.ilanToplam = ogrenciGiris.gorulenStajId + 0
            ogrenciGiris.save()

    if g.name == 'Öğrenci' or g.name == 'Mezun':
        return render(request, 'jobs/isilanlari.html', {'ilanlar': ilanlar, 'ogrenci': ogrenciGiris, 'bugun': bugun})
    else:
        return render(request, 'jobs/isilanlari.html', {'ilanlar': ilanlar, 'bugun': bugun})


def isİlaniDetay(request, pk):
    ilan = IsIlaniEkle.objects.get(pk=pk)
    return render(request, 'jobs/isilanlaridetay.html', {'ilan' :ilan})

def isİlaniGuncelle(request, pk):
    ilan = get_object_or_404(IsIlaniEkle, pk=pk)
    form = IsIlaniEkleForm(instance=ilan, data=request.POST or None)

    if form.is_valid():
        veri = form.save(commit=False)
        if veri.sonBasvuruTarihi == request.POST.get('sonBasvuruTarihi'):
            veri.save()
        else:
            veri.sonBasvuruTarihi = request.POST.get('sonBasvuruTarihi')
            veri.save()

        return redirect('jobs:ilanlarim')
    return render(request, 'jobs/updatejobs.html',{'form': form, 'ilan': ilan})

def isİlaniSil(request, pk):
    ilan = get_object_or_404(IsIlaniEkle, pk=pk)
    ilan.delete()
    return redirect('jobs:ilanlarim')


def ilanlarim(request):
    ilanlar = IsIlaniEkle.objects.filter(ilanSahibiMail=request.user.email)
    stajilanlar = stajIlani.objects.filter(stajIlanSahibiMail=request.user.email)

    return render(request, 'jobs/ilanlarim.html', {'ilanlar': ilanlar, 'stajilanlar': stajilanlar})


def stajIlaniEkle(request):
    if request.method == "POST":
        form = StajIlaniForm(request.POST)
        if form.is_valid():
            veri = form.save(commit=False)
            veri.stajIlanTarihi = datetime.datetime.now(tz=timezone.utc)
            veri.stajIlanSahibi = request.user.get_full_name()
            veri.stajIlanSahibiMail = request.user.email
            veri.stajSonBasvuruTarihi = request.POST.get('sonBasvuruTarihi')
            veri.save()
        return redirect('jobs:stajilanlari')
    else:
        form = StajIlaniForm(request.POST)
    return render(request, 'jobs/stajekle.html', {'form': form})

def stajİlaniGoruntule(request):
    ilanlar = stajIlani.objects.all()
    for g in request.user.groups.all():
        if g.name == 'Mezun':
            ogrenciGiris = Mezun.objects.get(user=request.user)
            ogrenciGiris.oncekiGirisStaj = datetime.datetime.now(tz=timezone.utc)
            ogrenciGiris.gorulenStajId = 0
            ogrenciGiris.ilanToplam = ogrenciGiris.gorulenIsId + 0
            ogrenciGiris.save()
        if g.name == 'Öğrenci':
            ogrenciGiris = Ogrenci.objects.get(user=request.user)
            ogrenciGiris.oncekiGirisStaj = datetime.datetime.now(tz=timezone.utc)
            ogrenciGiris.gorulenStajId = 0
            ogrenciGiris.ilanToplam = ogrenciGiris.gorulenIsId + 0
            ogrenciGiris.save()
        else:
            return render(request, 'jobs/stajilanlari.html', {'ilanlar': ilanlar})

    if g.name == 'Öğrenci' or g.name == 'Mezun':
        return render(request, 'jobs/stajilanlari.html', {'ilanlar': ilanlar, 'ogrenci': ogrenciGiris})
    else:
        return render(request, 'jobs/stajilanlari.html', {'ilanlar': ilanlar})

def stajİlaniDetay(request, pk):
    ilan = stajIlani.objects.get(pk=pk)
    return render(request, 'jobs/stajilanlaridetay.html', {'ilan' :ilan})

def stajİlaniGuncelle(request, pk):
    ilan = get_object_or_404(stajIlani, pk=pk)
    form = StajIlaniForm(instance=ilan, data=request.POST or None)

    if form.is_valid():
        veri = form.save(commit=False)
        if veri.stajSonBasvuruTarihi == request.POST.get('sonBasvuruTarihi'):
            veri.save()
        else:
            veri.stajSonBasvuruTarihi = request.POST.get('sonBasvuruTarihi')
            veri.save()

        return redirect('jobs:ilanlarim')
    return render(request, 'jobs/updatestajs.html',{'form': form, 'ilan': ilan})

def stajİlaniSil(request, pk):
    ilan = get_object_or_404(stajIlani, pk=pk)
    ilan.delete()
    return redirect('jobs:ilanlarim')

def bildirimIcin(request):
    global dersicerikMezun
    ilanlarIs = IsIlaniEkle.objects.all()
    ilanlarStaj = stajIlani.objects.all()
    for g in request.user.groups.all():
        if g.name == 'Mezun':
            ogrenci = Mezun.objects.get(user=request.user)
            transkriptler = TranskriptMezun.objects.filter(mail=request.user.email)
            randevular = randevuMezun.objects.filter(mail=request.user.email)
            dersicerikler = DersIcerikMezun.objects.filter(mail=request.user.email)
            ogrenci.gorulenStajId = 0
            ogrenci.gorulenIsId = 0
            ogrenci.gorulenTranskript = 0
            ogrenci.gorulenRandevu = 0
            ogrenci.gorulenDersIcerik = 0
            ogrenci.save()
            for stajIlan in ilanlarStaj:
                if stajIlan.stajIlanTarihi > ogrenci.oncekiGirisStaj:
                    ogrenci.gorulenStajId += 1
                    ogrenci.save()
            for isIlan in ilanlarIs:
                if isIlan.ilanTarihi > ogrenci.oncekiGirisIs:
                    ogrenci.gorulenIsId += 1
                    ogrenci.save()
            for transkript in transkriptler:
                for mezunMesaj in MesajMezun.objects.filter(transkript=transkript):
                    if mezunMesaj.mesajTarihi > ogrenci.oncekiGirisTranskript:
                        ogrenci.gorulenTranskript += 1
                        ogrenci.save()
            for randevu in randevular:
                for mezunMesaj in MesajRandevuMezun.objects.filter(randevu=randevu):
                    if mezunMesaj.mesajTarihi > ogrenci.oncekiGirisRandevu:
                        ogrenci.gorulenRandevu += 1
                        ogrenci.save()
            for dersIcerik in dersicerikler:
                for mezunMesaj in MesajdersMezun.objects.filter(dersicerik = dersIcerik):
                    if mezunMesaj.mesajTarihi > ogrenci.oncekiGirisDersIcerik:
                        ogrenci.gorulenDersIcerik += 1
                        ogrenci.save()
            ogrenci.ilanToplam = ogrenci.gorulenIsId + ogrenci.gorulenStajId
            ogrenci.save()
        if g.name == 'Öğrenci':
            ogrenci = Ogrenci.objects.get(user=request.user)
            transkriptler = TranskriptOgrenci.objects.filter(mail=request.user.email)
            randevular = randevuOgrenci.objects.filter(mail=request.user.email)
            ogrenci.gorulenStajId = 0
            ogrenci.gorulenIsId = 0
            ogrenci.gorulenTranskript = 0
            ogrenci.gorulenRandevu = 0
            ogrenci.save()
            for stajIlan in ilanlarStaj:
                if stajIlan.stajIlanTarihi > ogrenci.oncekiGirisStaj:
                    ogrenci.gorulenStajId += 1
                    ogrenci.save()
            for isIlan in ilanlarIs:
                if isIlan.ilanTarihi > ogrenci.oncekiGirisIs:
                    ogrenci.gorulenIsId += 1
                    ogrenci.save()
            for transkript in transkriptler:
                for ogrenciMesaj in MesajOgrenci.objects.filter(transkript=transkript):
                    if ogrenciMesaj.mesajTarihi > ogrenci.oncekiGirisTranskript:
                        ogrenci.gorulenTranskript += 1
                        ogrenci.save()
            for randevu in randevular:
                for ogrenciMesaj in MesajRandevuOgrenci.objects.filter(randevu=randevu):
                    if ogrenciMesaj.mesajTarihi > ogrenci.oncekiGirisRandevu:
                        ogrenci.gorulenRandevu += 1
                        ogrenci.save()
            ogrenci.ilanToplam = ogrenci.gorulenIsId + ogrenci.gorulenStajId
            ogrenci.save()
        if g.name == 'Bölüm Sekreteri':
            sekreter = BolumSekreteri.objects.get(user=request.user)
            ogrenciTranskriptler = TranskriptOgrenci.objects.all()
            mezunTranskriptler = TranskriptMezun.objects.all()
            sekreter.gorulenTranskriptMezun = 0
            sekreter.gorulenTranskriptOgrenci = 0
            sekreter.save()

templates/jobs/ilanlarim.html
{% extends 'base.html' %}
{% load static %}


{% block title %}İlanlarım{% endblock %}

{% block head %}
<script type="text/javascript" src="{% static 'js/haberEtkinlik.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/haberEtkinlik.css' %}" type="text/css">
{% endblock %}

{% block body %}

<div class="container" style="width: 730px; background-color: deepskyblue; margin-bottom: 40px; margin-top: 50px;
-webkit-border-radius: 10px; -moz-border-radius: 10px; border-radius: 10px 10px 10px 10px;">

{% for ilan in ilanlar %}
<div class="container" style="background-color: #204d74; color: white; width: 700px; margin-bottom: 20px; margin-top: 20px;
     -webkit-border-radius: 10px; -moz-border-radius: 10px; border-radius: 10px 10px 10px 10px;  -moz-box-shadow: 4px 4px 4px #1E90FF; -webkit-box-shadow: 4px 4px 4px #1E90FF;">


    <legend style="color: white;"><b>
        <label style="margin-top: 10px; margin-bottom: 5px; font-size: 20px;">İş İlanı : </label>
        {{ilan.isOzeti}}
    </b></legend>
    <div class="row" style="margin-left: 5px;">

        <div class="form-group row">
            <div class="col-sm-2" style="margin-top: 5px;">
                <span class="glyphicon glyphicon-briefcase"></span>
                <label class="col-form-label">Firma Adı:</label>
            </div>
            <div class="col-sm-10">
                {{ilan.firma}}
            </div>
        </div>

        <div class="form-group row">
                <div class="col-sm-2" style="margin-top: 5px;">
                    <span class="glyphicon glyphicon-map-marker"></span>
                    <label class="col-form-label">İl/İlçe:</label>
                </div>
        <div class="col-sm-10">
            {{ilan.konum}}
        </div>
    </div>

        <div class="form-group row">

            <div class="col-sm-2" style="margin-top: 5px;">
        <span class="glyphicon glyphicon-calendar"></span>
            <label class="col-form-label">İlan Tarihi:</label>
    </div>
    <div class="col-sm-10">
        {{ilan.ilanTarihi|date:"SHORT_DATE_FORMAT"}}

        <button class="btn btn-danger pull-right" type="submit" onclick="location.href='{% url 'jobs:ilansil' ilan.pk %}';" style="margin-right: 20px; width: 100px;">Sil</button>
        <button class="btn btn-warning pull-right" type="submit" onclick="location.href='{% url 'jobs:ilanguncelle' ilan.pk %}';" style="margin-right: 20px; width: 100px;">Güncelle</button>
        <button class="btn btn-info pull-right" type="submit" onclick="location.href='{% url 'jobs:ilandetay' ilan.pk %}';" style="margin-right: 20px; width: 100px;">Görüntüle</button>
    </div>

</div>
</div>
</div>

{% endfor %}

{% for stajilan in stajilanlar %}
<div class="container" style="background-color: #204d74; color :white; width: 700px; margin-bottom: 20px; margin-top: 20px;
    -webkit-border-radius: 10px; -moz-border-radius: 10px; border-radius: 10px 10px 10px 10px; -moz-box-shadow: 4px 4px 4px #1E90FF; -webkit-box-shadow: 4px 4px 4px #1E90FF;">


    <legend style="color: white;"><b>
        <label  style="margin-top: 10px; margin-bottom: 5px; font-size: 20px;">Staj İlanı : </label>
        {{stajilan.stajBaslik}}
    </b></legend>
    <div class="row" style="margin-left: 5px;">

        <div class="form-group row">
            <div class="col-sm-2" style="margin-top: 5px;">
                <span class="glyphicon glyphicon-briefcase"></span>
                <label class="col-form-label">Firma Adı:</label>
            </div>
            <div class="col-sm-10">
                {{stajilan.stajFirma}}
            </div>
        </div>

        <div class="form-group row">
                <div class="col-sm-2" style="margin-top: 5px;">
            <span class="glyphicon glyphicon-map-marker"></span>
                <label class="col-form-label">İl/İlçe:</label>
        </div>
        <div class="col-sm-10">
            {{stajilan.stajKonum}}
        </div>
    </div>

    <div class="form-group row">
            <div class="col-sm-2" style="margin-top: 5px;">
        <span class="glyphicon glyphicon-calendar"></span>
            <label class="col-form-label">İlan Tarihi:</label>
    </div>
    <div class="col-sm-10">
        {{stajilan.stajIlanTarihi|date:"SHORT_DATE_FORMAT"}}

        <button class="btn btn-danger pull-right" type="submit" onclick="location.href='{% url 'jobs:stajilanisil' stajilan.pk %}';" style="margin-right: 20px; width: 100px;">Sil</button>
        <button class="btn btn-warning pull-right" type="submit" onclick="location.href='{% url 'jobs:stajilaniguncelle' stajilan.pk %}';" style="margin-right: 20px; width: 100px;">Güncelle</button>
        <button class="btn btn-info pull-right" type="submit" onclick="location.href='{% url 'jobs:stajilanidetay' stajilan.pk %}';" style="margin-right: 20px; width: 100px;">Görüntüle</button>
    </div>

</div>
</div>
</div>

{% endfor %}


</div>
{% endblock %}

templates/jobs/isilanlari.html
{% extends 'base.html' %}
{% load static %}
{% block kullanici %}
{{ user.get_full_name }}
{% endblock %}

{% block title %}İş İlanları İncele{% endblock %}

{% block head %}
<script type="text/javascript" src="{% static 'js/haberEtkinlik.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/haberEtkinlik.css' %}" type="text/css">
{% endblock %}

{% block body %}
<div class="container" style="margin-top: 50px; margin-bottom: 50px; background-color: #333; width: 730px; -webkit-border-radius: 10px; -moz-border-radius: 10px; border-radius: 10px 10px 10px 10px;">

    {% for ilan in ilanlar %}

    {% if ilan.sonBasvuruTarihi.year > bugun.year %}
        <div class="container"
             style="background-color: #666; width: 700px; margin-bottom: 15px; margin-top: 15px; color: white; -webkit-border-radius: 5px; -moz-border-radius: 5px; border-radius: 5px 5px 5px 5px; -moz-box-shadow: 2px 2px 2px #1E90FF; -webkit-box-shadow: 2px 2px 2px #1E90FF;">


            <legend><b><p style="margin-top: 10px; margin-bottom: 5px; font-size: 20px; color: white;">
                {{ilan.isOzeti}}</p>
            </b></legend>
            <div class="row" style="margin-left: 5px; font-size: 14px">
                <div class="form-group row col-lg-10" style="margin-top: 5px;">
                    <p>
                        <span class="glyphicon glyphicon-briefcase" style="margin-left: 20px;"></span>
                        {{ilan.firma}}<br>
                        <span class="glyphicon glyphicon-map-marker" style="margin-left: 20px;"></span>
                        {{ilan.konum}}<br>
                        <span class="glyphicon glyphicon-calendar" style="margin-left: 20px;"></span>
                        {{ilan.ilanTarihi|date:"SHORT_DATE_FORMAT"}} - {{ilan.sonBasvuruTarihi|date:"SHORT_DATE_FORMAT"}}
                    </p>
                </div>

                <div class="col-lg-2">
                    <br>
                    <button class="btn btn-info pull-right" type="submit" onclick="location.href='{% url 'jobs:ilandetay' ilan.pk %}';" style="margin-right: 20px; width: 100px;">İncele</button>
                </div>
            </div>
        </div>

    {% elif ilan.sonBasvuruTarihi.year == bugun.year %}
        {% if ilan.sonBasvuruTarihi.month > bugun.month %}

            <div class="container"
             style="background-color: #666; width: 700px; margin-bottom: 15px; margin-top: 15px; color: white; -webkit-border-radius: 5px; -moz-border-radius: 5px; border-radius: 5px 5px 5px 5px; -moz-box-shadow: 2px 2px 2px #1E90FF; -webkit-box-shadow: 2px 2px 2px #1E90FF;">


            <legend><b><p style="margin-top: 10px; margin-bottom: 5px; font-size: 20px; color: white;">
                {{ilan.isOzeti}}</p>
            </b></legend>
            <div class="row" style="margin-left: 5px; font-size: 14px">
                <div class="form-group row col-lg-10" style="margin-top: 5px;">
                    <p>
                        <span class="glyphicon glyphicon-briefcase" style="margin-left: 20px;"></span>
                        {{ilan.firma}}<br>
                        <span class="glyphicon glyphicon-map-marker" style="margin-left: 20px;"></span>
                        {{ilan.konum}}<br>
                        <span class="glyphicon glyphicon-calendar" style="margin-left: 20px;"></span>
                        {{ilan.ilanTarihi|date:"SHORT_DATE_FORMAT"}} - {{ilan.sonBasvuruTarihi|date:"SHORT_DATE_FORMAT"}}
                    </p>
                </div>

                <div class="col-lg-2">
                    <br>
                    <button class="btn btn-info pull-right" type="submit" onclick="location.href='{% url 'jobs:ilandetay' ilan.pk %}';" style="margin-right: 20px; width: 100px;">İncele</button>
                </div>
            </div>
        </div>

        {% elif ilan.sonBasvuruTarihi.month == bugun.month %}

            {% if ilan.sonBasvuruTarihi.day >= bugun.day %}

                <div class="container"
             style="background-color: #666; width: 700px; margin-bottom: 15px; margin-top: 15px; color: white; -webkit-border-radius: 5px; -moz-border-radius: 5px; border-radius: 5px 5px 5px 5px; -moz-box-shadow: 2px 2px 2px #1E90FF; -webkit-box-shadow: 2px 2px 2px #1E90FF;">


            <legend><b><p style="margin-top: 10px; margin-bottom: 5px; font-size: 20px; color: white;">
                {{ilan.isOzeti}}</p>
            </b></legend>
            <div class="row" style="margin-left: 5px; font-size: 14px">
                <div class="form-group row col-lg-10" style="margin-top: 5px;">
                    <p>
                        <span class="glyphicon glyphicon-briefcase" style="margin-left: 20px;"></span>
                        {{ilan.firma}}<br>
                        <span class="glyphicon glyphicon-map-marker" style="margin-left: 20px;"></span>
                        {{ilan.konum}}<br>
                        <span class="glyphicon glyphicon-calendar" style="margin-left: 20px;"></span>
                        {{ilan.ilanTarihi|date:"SHORT_DATE_FORMAT"}} - {{ilan.sonBasvuruTarihi|date:"SHORT_DATE_FORMAT"}}
                    </p>
                </div>

                <div class="col-lg-2">
                    <br>
                    <button class="btn btn-info pull-right" type="submit" onclick="location.href='{% url 'jobs:ilandetay' ilan.pk %}';" style="margin-right: 20px; width: 100px;">İncele</button>
                </div>
            </div>
        </div>

            {% endif %}
        {% endif %}


    {% endif %}
{% endfor %}
</div>
{% endblock %}